version: '2'
services:
  email_signature_generator-app:
    image: email_signature_generator
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://email_signature_generator-postgresql:5432/email_signature_generator
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  email_signature_generator-postgresql:
    extends:
      file: postgresql.yml
      service: email_signature_generator-postgresql
